# Generated by Django 4.2.4 on 2023-09-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='username',
        ),
    ]
